version: "3.9"
services:
  mysql:
    image: mysql:8.0
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - TZ=Asia/Tokyo

  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: sessions
        target: /sessions
        volume:
          nocopy: true
    environment: 
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
    links: 
      - mysql
volumes:
  db-store:
  sessions: